version: '2.1'

services:
  issmoexproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: issmoexproxy-build
    volumes:
      - .:/root
    command: >
      bash -c '/root/build.sh && exit'

